/**
 * Cat Application API
 * Mobilszoftver laboratórium házi feladat API leírása
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.moblab.hw.catapplication.model


/**
 *
 * @param id
 * @param name
 * @param temperament
 * @param lifeSpan
 * @param altNames
 * @param wikipediaUrl
 * @param origin
 * @param weightImperial
 * @param experimental
 * @param hairless
 * @param natural
 * @param rare
 * @param rex
 * @param suppressTail
 * @param shortLegs
 * @param hypoallergenic
 * @param adaptability
 * @param affectionLevel
 * @param countryCore
 * @param childFriendly
 * @param dogFriendly
 * @param energyLevel
 * @param grooming
 * @param healthIssues
 * @param intelligence
 * @param sheddingLevel
 * @param socialNeeds
 * @param strangerFriendly
 * @param vocalistaion
 */
data class BreedResult(
    val id: String? = null,
    val name: String? = null,
    val temperament: String? = null,
    val lifeSpan: String? = null,
    val altNames: String? = null,
    val wikipediaUrl: String? = null,
    val origin: String? = null,
    val weightImperial: String? = null,
    val experimental: Int? = null,
    val hairless: Int? = null,
    val natural: Int? = null,
    val rare: Int? = null,
    val rex: Int? = null,
    val suppressTail: Int? = null,
    val shortLegs: Int? = null,
    val hypoallergenic: Int? = null,
    val adaptability: Int? = null,
    val affectionLevel: Int? = null,
    val countryCore: String? = null,
    val childFriendly: Int? = null,
    val dogFriendly: Int? = null,
    val energyLevel: Int? = null,
    val grooming: Int? = null,
    val healthIssues: Int? = null,
    val intelligence: Int? = null,
    val sheddingLevel: Int? = null,
    val socialNeeds: Int? = null,
    val strangerFriendly: Int? = null,
    val vocalistaion: Int? = null
)

fun BreedResult.toModel() = CatBreedModel(
    id,
    name,
    temperament,
    lifeSpan,
    altNames,
    wikipediaUrl,
    origin,
    weightImperial,
    experimental,
    hairless,
    natural,
    rare,
    rex,
    suppressTail,
    shortLegs,
    hypoallergenic,
    adaptability,
    affectionLevel,
    countryCore,
    childFriendly,
    dogFriendly,
    energyLevel,
    grooming,
    healthIssues,
    intelligence,
    sheddingLevel,
    socialNeeds,
    strangerFriendly,
    vocalistaion
)