/**
 * Cat Application API
 * Mobilszoftver laboratórium házi feladat API leírása
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.moblab.hw.catapplication.model


/**
 * 
 * @param id 
 * @param name 
 * @param temperament 
 * @param lifeSpan 
 * @param altNames 
 * @param wikipediaUrl 
 * @param origin 
 * @param weightImperial 
 * @param experimental 
 * @param hairless 
 * @param natural 
 * @param rare 
 * @param rex 
 * @param suppressTail 
 * @param shortLegs 
 * @param hypoallergenic 
 * @param adaptability 
 * @param affectionLevel 
 * @param countryCore 
 * @param childFriendly 
 * @param dogFriendly 
 * @param energyLevel 
 * @param grooming 
 * @param healthIssues 
 * @param intelligence 
 * @param sheddingLevel 
 * @param socialNeeds 
 * @param strangerFriendly 
 * @param vocalistaion 
 */
data class BreedResult (

    val id: kotlin.String? = null,
    val name: kotlin.String? = null,
    val temperament: kotlin.String? = null,
    val lifeSpan: kotlin.String? = null,
    val altNames: kotlin.String? = null,
    val wikipediaUrl: kotlin.String? = null,
    val origin: kotlin.String? = null,
    val weightImperial: kotlin.String? = null,
    val experimental: java.math.BigDecimal? = null,
    val hairless: java.math.BigDecimal? = null,
    val natural: java.math.BigDecimal? = null,
    val rare: java.math.BigDecimal? = null,
    val rex: java.math.BigDecimal? = null,
    val suppressTail: java.math.BigDecimal? = null,
    val shortLegs: java.math.BigDecimal? = null,
    val hypoallergenic: java.math.BigDecimal? = null,
    val adaptability: java.math.BigDecimal? = null,
    val affectionLevel: java.math.BigDecimal? = null,
    val countryCore: kotlin.String? = null,
    val childFriendly: java.math.BigDecimal? = null,
    val dogFriendly: java.math.BigDecimal? = null,
    val energyLevel: java.math.BigDecimal? = null,
    val grooming: java.math.BigDecimal? = null,
    val healthIssues: java.math.BigDecimal? = null,
    val intelligence: java.math.BigDecimal? = null,
    val sheddingLevel: java.math.BigDecimal? = null,
    val socialNeeds: java.math.BigDecimal? = null,
    val strangerFriendly: java.math.BigDecimal? = null,
    val vocalistaion: java.math.BigDecimal? = null
) {
}