/**
 * Cat Application API
 * Mobilszoftver laboratórium házi feladat API leírása
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.moblab.hw.catapplication.model

import io.swagger.client.models.FactStatusResult

/**
 * 
 * @param id 
 * @param used 
 * @param source 
 * @param type 
 * @param deleted 
 * @param user 
 * @param text 
 * @param updatedAt 
 * @param createdAt 
 * @param status 
 */
data class FactResult (

    val id: kotlin.String? = null,
    val used: kotlin.Boolean? = null,
    val source: kotlin.String? = null,
    val type: kotlin.String? = null,
    val deleted: kotlin.Boolean? = null,
    val user: kotlin.String? = null,
    val text: kotlin.String? = null,
    val updatedAt: kotlin.String? = null,
    val createdAt: kotlin.String? = null,
    val status: FactStatusResult? = null
) {
}