/**
 * Cat Application API
 * Mobilszoftver laboratórium házi feladat API leírása
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.bme.aut.moblab.hw.catapplication.model


/**
 * 
 * @param verified 
 * @param sentCount 
 */
data class FactStatusResult (

    val verified: Boolean? = null,
    val sentCount: Int? = null
)